title: Oriol Corcoll Blog
description: >
  Future description.
copyright: Oriol Corcoll
sass:
  sass_dir: assets/sass
url: http://localhost:4000
disqus_shortname: ocorcoll
facebook_username:
twitter_username: "ocorcoll"
linkedin_username: "ocorcoll"
instagram_username:
pinterest_username:
flickr_username:
github_username:  "ocorcoll"
feed_icon: rss
email: "ocorcoll at gmail dot com"
gems: [jekyll-paginate]
paginate_path: "/page/:num/"
paginate: 5
